apiVersion: batch/v1
kind: Job
metadata:
  name: ks-alerting-migration
  namespace: kubesphere-system
  labels:
    app: ks-alerting-migration
    job: ks-alerting-migration
    version: v3.1.0
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: ks-alerting-migration
        job: ks-alerting-migration
        version: v3.1.0
      name: ks-alerting-migration
    spec:
      initContainers:
        - name: wait-mysql
          image: alpine:3.10.4
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nc -z mysql.kubesphere-system.svc 3306; do echo "waiting for mysql"; sleep 2; done;']
        - name: wait-apiserver
          image: alpine:3.10.4
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nc -z ks-apiserver.kubesphere-system.svc 80; do echo "waiting for apiserver"; sleep 2; done;']
      containers:
        - image: kubespheredev/ks-alerting-migration:v3.1.0
          imagePullPolicy: IfNotPresent
          name: ks-alerting-migration
      serviceAccount: kubesphere
      serviceAccountName: kubesphere
      restartPolicy: OnFailure