apiVersion: v1
kind: Service
metadata:
  {{- with .Values.cloudCore.labels }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
  name: edgeservice
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    {{- with .Values.cloudCore.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}