---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ks-controller-manager
    tier: backend
    version: v3.1.0
  name: ks-controller-manager
  namespace: kubesphere-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: ks-controller-manager
    tier: backend
    version: v3.1.0
  sessionAffinity: None
  type: ClusterIP