---

- name: istio | Check istio
  shell: >
    {{ bin_dir }}/kubectl get pods -n istio-system | grep "istiod"
  register: istio_check
  failed_when: false

- block:
    - name: istio | Getting istio installation files
      copy:
        src: "{{ item }}"
        dest: "{{ kubesphere_dir }}/"
      loop:
        - "istio"

    # label istio-system with istio-injection=disabled to avoid sidecarInjector mutatingwebhookconfigurations block pod creation
    - name: istio | disable istio-injection
      shell: >
        {{ bin_dir }}/kubectl label ns {{ item }} istio-injection=disabled --overwrite
      loop:
        - istio-system
        - kube-system
        - kubesphere-system
        - kubesphere-devops-system
      ignore_errors: True

    - name: istio | Unarchive istio files
      shell: >
        tar -zxf {{ kubesphere_dir }}/istio/istio-1.6.10-linux-amd64.tar.gz -C {{ kubesphere_dir }}/istio/

    - name: istio | Deploy istio
      shell: >
        {{ kubesphere_dir }}/istio/istio-1.6.10/bin/istioctl install -f {{ kubesphere_dir }}/istio/istio-profile-1.6.10.yaml
      register: istio_result
      failed_when: "'errors occurred during operation' in istio_result.stderr"

    - name: istio | Check jaeger-operator
      shell: >
        {{ bin_dir }}/helm list -n istio-system | grep "jaeger-operator"
      register: jaeger_check
      failed_when: false

    - name: istio | Delete jaeger-operator deployment
      shell: >
        {{ bin_dir }}/kubectl delete deploy -n istio-system jaeger-operator
      when:
        - (jaeger_check.stdout.find("deployed") != -1) and (jaeger_check.stdout.find("1.17.1") == -1)

    - name: istio | Creating jaeger manifests
      template:
        src: "{{ item.file }}.j2"
        dest: "{{ kubesphere_dir }}/{{ item.path }}/{{ item.file }}"
      with_items:
        - { path: istio, file: custom-values-jaeger.yaml }
        - { path: istio, file: jaeger-production.yaml }

    - name: istio | Deploy jaeger-operator
      shell: >
        {{ bin_dir }}/helm upgrade --install jaeger-operator {{ kubesphere_dir }}/istio/jaeger-operator
        -f {{ kubesphere_dir }}/istio/custom-values-jaeger.yaml
        --namespace istio-system
      when:
        - (jaeger_check.stdout.find("deployed") == -1) or (jaeger_check.stdout.find("1.17.1") == -1)

    - name: istio | Deploy jaeger-production
      shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/istio/jaeger-production.yaml --namespace istio-system"
      register: import
      until: import is succeeded
      retries: 5
      delay: 10
      when:
        - (jaeger_check.stdout.find("deployed") == -1) or (jaeger_check.stdout.find("1.17.1") == -1)

    - name: istio | Create jaeger operator service
      shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/istio/jaeger-operator-service.yaml --namespace istio-system"
      register: import
      until: import is succeeded
      retries: 5
      delay: 10
      when:
        - (jaeger_check.stdout.find("deployed") == -1) or (jaeger_check.stdout.find("1.17.1") == -1)
  when:
    - (istio_check.stdout.find("Running") == -1)

- name: servicemesh | import servicemesh status
  shell: >
    {{ bin_dir }}/kubectl patch cc ks-installer
    --type merge
    -p '{"status": {"servicemesh": {"status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}}}'
    -n kubesphere-system
  register: import
  failed_when: "import.stderr and 'Warning' not in import.stderr"
  until: import is succeeded
  retries: 5
  delay: 3
